# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  apple-emoji = {
    pname = "apple-emoji";
    version = "v18.4";
    src = fetchurl {
      url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/v18.4/AppleColorEmoji.ttf";
      sha256 = "sha256-pP0He9EUN7SUDYzwj0CE4e39SuNZ+SVz7FdmUviF6r0=";
    };
  };
  base16-schemes = {
    pname = "base16-schemes";
    version = "43dd14f6466a782bd57419fdfb5f398c74d6ac53";
    src = fetchgit {
      url = "https://github.com/tinted-theming/schemes.git";
      rev = "43dd14f6466a782bd57419fdfb5f398c74d6ac53";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AWTIYZ1tZab0YwAQwgt5yO4ucqZoc4iXX002Byy7pRY=";
    };
    date = "2026-01-15";
  };
  dzgui = {
    pname = "dzgui";
    version = "2d58bb491e44acff34aa9b4b4bda44ba2b057575";
    src = fetchgit {
      url = "https://codeberg.org/aclist/dztui";
      rev = "2d58bb491e44acff34aa9b4b4bda44ba2b057575";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5MGYhoo5V6tNDXV61z15kLMVFMnWfblKMeLEXEBkBj0=";
    };
    date = "2026-01-17";
  };
  equibop-bin = {
    pname = "equibop-bin";
    version = "3.1.6";
    src = fetchurl {
      url = "https://github.com/Equicord/Equibop/releases/download/v3.1.6/Equibop-3.1.6-universal.dmg";
      sha256 = "sha256-vWx/woOEQWTKrbujgCw5JDPaTZMPpK0YEaiZj7VBsdM=";
    };
  };
  helium-dmg = {
    pname = "helium-dmg";
    version = "0.8.2.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-macos/releases/download/0.8.2.1/helium_0.8.2.1_arm64-macos.dmg";
      sha256 = "sha256-Y42Fj+5KPZ2aO7XazV1CFB7liAmWSsafcXpvukJRqoM=";
    };
  };
  helium-tarball = {
    pname = "helium-tarball";
    version = "0.8.2.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.8.2.1/helium-0.8.2.1-x86_64_linux.tar.xz";
      sha256 = "sha256-hljL7KlafD1TYPmA+U8HRdXKOUdsb6Lnk4XiAYfmPI8=";
    };
  };
  liga-sf-mono-nerd-font = {
    pname = "liga-sf-mono-nerd-font";
    version = "dc5a3e6fcc2e16ad476b7be3c3c17c2273b260ea";
    src = fetchgit {
      url = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized.git";
      rev = "dc5a3e6fcc2e16ad476b7be3c3c17c2273b260ea";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AYjKrVLISsJWXN6Cj74wXmbJtREkFDYOCRw1t2nVH2w=";
    };
    date = "2023-07-01";
  };
  morewaita-icon-theme = {
    pname = "morewaita-icon-theme";
    version = "v49";
    src = fetchgit {
      url = "https://github.com/somepaulo/MoreWaita.git";
      rev = "v49";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DxZ7XnIIF3EKGMPXahD+aHp6lCLRmrnywn7+qWCVflo=";
    };
  };
  owo-sh = {
    pname = "owo-sh";
    version = "d6ffda964cd6c81030f8e5516ca57c80a5a5dcb2";
    src = fetchgit {
      url = "https://owo.codes/whats-this/owo.sh.git";
      rev = "d6ffda964cd6c81030f8e5516ca57c80a5a5dcb2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-vwvUiM7mOixyNERjITwcS90jz15QFkwxCEtYzqm+hdg=";
    };
    date = "2023-04-10";
  };
  pearcleaner-bin = {
    pname = "pearcleaner-bin";
    version = "5.4.3";
    src = fetchurl {
      url = "https://github.com/alienator88/Pearcleaner/releases/download/5.4.3/Pearcleaner.dmg";
      sha256 = "sha256-+hTyxyRhCbM3OzRiqoFxel+iSIr6QcpcWoc4TIh0mqY=";
    };
  };
  proton-cachyos_x86_64_v3 = {
    pname = "proton-cachyos_x86_64_v3";
    version = "cachyos-10.0-20260102-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-10.0-20260102-slr/proton-cachyos-10.0-20260102-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-bDlgsRNxA35YW91AsXhvA7dLsSq6cZ8Umczbw+Zj+2k=";
    };
  };
  proton-cachyos_x86_64_v4 = {
    pname = "proton-cachyos_x86_64_v4";
    version = "cachyos-10.0-20260102-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-10.0-20260102-slr/proton-cachyos-10.0-20260102-slr-x86_64_v4.tar.xz";
      sha256 = "sha256-e2A9jrAGUHlD8KUuGjkLUhknclBxVZVYKJFElUEs0Us=";
    };
  };
  protonmail-bin = {
    pname = "protonmail-bin";
    version = "1.12.0";
    src = fetchurl {
      url = "https://proton.me/download/mail/macos/1.12.0/ProtonMail-desktop.dmg";
      sha256 = "sha256-34KO4h2t95k2o2JREyK5jFdTc5ONuRdFEYuQSjlvNkA=";
    };
  };
  protonpass-bin = {
    pname = "protonpass-bin";
    version = "1.33.5";
    src = fetchurl {
      url = "https://proton.me/download/PassDesktop/darwin/universal/ProtonPass_1.33.5.dmg";
      sha256 = "sha256-yTLSCJ9TpTfe5jThBY7nivT9pQwjvmHMp6IUZLCg9kk=";
    };
  };
  protonvpn-bin = {
    pname = "protonvpn-bin";
    version = "6.1.0";
    src = fetchurl {
      url = "https://vpn.protondownload.com/download/macos/6.1.0/ProtonVPN_mac_v6.1.0.dmg";
      sha256 = "sha256-u/J32eIgpQkvF87j4Lc3IKT0YkJHTx4JauL6TsXg/ls=";
    };
  };
  swipeaerospace-bin = {
    pname = "swipeaerospace-bin";
    version = "0.2.5";
    src = fetchurl {
      url = "https://github.com/MediosZ/SwipeAeroSpace/releases/download/0.2.5/SwipeAeroSpace.zip";
      sha256 = "sha256-v3zjXCxCS2Vsjqoc+vYvbN3hiBKy2Jh+uIrG2ZSPmn0=";
    };
  };
  wheelwizard = {
    pname = "wheelwizard";
    version = "2.3.4";
    src = fetchgit {
      url = "https://github.com/TeamWheelWizard/WheelWizard.git";
      rev = "2.3.4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-EWNknLymehCcxXygsuo5jKrtWUNP3TnLr3H+Q3T2Ygs=";
    };
  };
}
