# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  apple-emoji = {
    pname = "apple-emoji";
    version = "v18.4";
    src = fetchurl {
      url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/v18.4/AppleColorEmoji.ttf";
      sha256 = "sha256-pP0He9EUN7SUDYzwj0CE4e39SuNZ+SVz7FdmUviF6r0=";
    };
  };
  barik = {
    pname = "barik";
    version = "0.5.1";
    src = fetchurl {
      url = "https://github.com/mocki-toki/barik/releases/download/0.5.1/Barik.zip";
      sha256 = "sha256-yFglQoP7wJaqpOYd0VvnoKxWVZUSnSKFKVq5M7XgYLU=";
    };
  };
  base16-schemes = {
    pname = "base16-schemes";
    version = "317a5e10c35825a6c905d912e480dfe8e71c7559";
    src = fetchgit {
      url = "https://github.com/tinted-theming/schemes.git";
      rev = "317a5e10c35825a6c905d912e480dfe8e71c7559";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-d4km8W7w2zCUEmPAPUoLk1NlYrGODuVa3P7St+UrqkM=";
    };
    date = "2025-09-13";
  };
  gpu-screen-recorder-notification = {
    pname = "gpu-screen-recorder-notification";
    version = "a205222cf499e4f4ec701b91c3323499c424e8e8";
    src = fetchgit {
      url = "https://repo.dec05eba.com/gpu-screen-recorder-notification";
      rev = "a205222cf499e4f4ec701b91c3323499c424e8e8";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ODifZ046DEBNiGT3+S6pQyF8ekrb6LIHWton8nv1MBo=";
    };
    date = "2025-09-28";
  };
  gpu-screen-recorder-ui = {
    pname = "gpu-screen-recorder-ui";
    version = "ccf96030da52bf344b21b349812792961dfd0fc7";
    src = fetchgit {
      url = "https://repo.dec05eba.com/gpu-screen-recorder-ui";
      rev = "ccf96030da52bf344b21b349812792961dfd0fc7";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Ul/jEcgmMiO3EK2wl9MLLBccLEOjV8kgWy+glLrss/4=";
    };
    date = "2025-10-03";
  };
  helium-browser-bin = {
    pname = "helium-browser-bin";
    version = "0.4.13.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-macos/releases/download/0.4.13.1/helium_0.4.13.1_arm64-macos.dmg";
      sha256 = "sha256-3j4souWY+4EGPSQR6uURjyqu3bkB5G9xuJbvOk9cZd8=";
    };
  };
  liga-sf-mono-nerd-font = {
    pname = "liga-sf-mono-nerd-font";
    version = "dc5a3e6fcc2e16ad476b7be3c3c17c2273b260ea";
    src = fetchgit {
      url = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized.git";
      rev = "dc5a3e6fcc2e16ad476b7be3c3c17c2273b260ea";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AYjKrVLISsJWXN6Cj74wXmbJtREkFDYOCRw1t2nVH2w=";
    };
    date = "2023-07-01";
  };
  owo-sh = {
    pname = "owo-sh";
    version = "d6ffda964cd6c81030f8e5516ca57c80a5a5dcb2";
    src = fetchgit {
      url = "https://owo.codes/whats-this/owo.sh.git";
      rev = "d6ffda964cd6c81030f8e5516ca57c80a5a5dcb2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-vwvUiM7mOixyNERjITwcS90jz15QFkwxCEtYzqm+hdg=";
    };
    date = "2023-04-10";
  };
  wheelwizard = {
    pname = "wheelwizard";
    version = "2.3.3";
    src = fetchgit {
      url = "https://github.com/TeamWheelWizard/WheelWizard.git";
      rev = "2.3.3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DuEI6bmvNP6wRuZX9Do0FGDsu80ldy0SCefBk6gqT9s=";
    };
  };
}
