# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  apple-emoji = {
    pname = "apple-emoji";
    version = "v18.4";
    src = fetchurl {
      url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/v18.4/AppleColorEmoji.ttf";
      sha256 = "sha256-pP0He9EUN7SUDYzwj0CE4e39SuNZ+SVz7FdmUviF6r0=";
    };
  };
  base16-schemes = {
    pname = "base16-schemes";
    version = "0f6be815d258e435c9b137befe5ef4ff24bea32c";
    src = fetchgit {
      url = "https://github.com/tinted-theming/schemes.git";
      rev = "0f6be815d258e435c9b137befe5ef4ff24bea32c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Hju0WtMf3iForxtOwXqGp3Ynipo0EYx1AqMKLPp9BJw=";
    };
    date = "2025-11-23";
  };
  dzgui = {
    pname = "dzgui";
    version = "a1d14669c7139c764bf14fceeac9f26e7d38750d";
    src = fetchgit {
      url = "https://codeberg.org/aclist/dztui";
      rev = "a1d14669c7139c764bf14fceeac9f26e7d38750d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-o00Qon4lB/RICiHT/MI0hXUMmyctnYH469rOGB8V/HI=";
    };
    date = "2025-10-30";
  };
  gpu-screen-recorder-notification = {
    pname = "gpu-screen-recorder-notification";
    version = "54e4f30a692b7f86686d531d0331de32374a4735";
    src = fetchgit {
      url = "https://repo.dec05eba.com/gpu-screen-recorder-notification";
      rev = "54e4f30a692b7f86686d531d0331de32374a4735";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-aLoDDbhhLUZl/2Zt0swhtD4/vqDEAnbVPKcFhqxvpsQ=";
    };
    date = "2025-10-04";
  };
  gpu-screen-recorder-ui = {
    pname = "gpu-screen-recorder-ui";
    version = "2c2633ec58fa14ca452d94c7b0ea5ae720ceec19";
    src = fetchgit {
      url = "https://repo.dec05eba.com/gpu-screen-recorder-ui";
      rev = "2c2633ec58fa14ca452d94c7b0ea5ae720ceec19";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-y9GDFclLFDHhXSzpSNTo8VeRKMJgRXjH6HcQSIgDciQ=";
    };
    date = "2025-12-01";
  };
  helium-dmg = {
    pname = "helium-dmg";
    version = "0.6.9.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-macos/releases/download/0.6.9.1/helium_0.6.9.1_arm64-macos.dmg";
      sha256 = "sha256-zqgZNZ9qKCtW7hTATtkBidXGaOHXY4yDk4tJTU3ftZw=";
    };
  };
  helium-tarball = {
    pname = "helium-tarball";
    version = "0.6.9.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.6.9.1/helium-0.6.9.1-x86_64_linux.tar.xz";
      sha256 = "sha256-DLcJCECE5yWcwZuRwNJs3q+sqrZbTbouGF5bDTIFYWM=";
    };
  };
  liga-sf-mono-nerd-font = {
    pname = "liga-sf-mono-nerd-font";
    version = "dc5a3e6fcc2e16ad476b7be3c3c17c2273b260ea";
    src = fetchgit {
      url = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized.git";
      rev = "dc5a3e6fcc2e16ad476b7be3c3c17c2273b260ea";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AYjKrVLISsJWXN6Cj74wXmbJtREkFDYOCRw1t2nVH2w=";
    };
    date = "2023-07-01";
  };
  owo-sh = {
    pname = "owo-sh";
    version = "d6ffda964cd6c81030f8e5516ca57c80a5a5dcb2";
    src = fetchgit {
      url = "https://owo.codes/whats-this/owo.sh.git";
      rev = "d6ffda964cd6c81030f8e5516ca57c80a5a5dcb2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-vwvUiM7mOixyNERjITwcS90jz15QFkwxCEtYzqm+hdg=";
    };
    date = "2023-04-10";
  };
  pearcleaner-bin = {
    pname = "pearcleaner-bin";
    version = "5.4.3";
    src = fetchurl {
      url = "https://github.com/alienator88/Pearcleaner/releases/download/5.4.3/Pearcleaner.dmg";
      sha256 = "sha256-+hTyxyRhCbM3OzRiqoFxel+iSIr6QcpcWoc4TIh0mqY=";
    };
  };
  protonmail-bin = {
    pname = "protonmail-bin";
    version = "1.11.0";
    src = fetchurl {
      url = "https://proton.me/download/mail/macos/1.11.0/ProtonMail-desktop.dmg";
      sha256 = "sha256-IPOHSSHxdSaLkYX0deH1RFpi17liq0tenfpNniAlNUc=";
    };
  };
  protonpass-bin = {
    pname = "protonpass-bin";
    version = "1.33.0";
    src = fetchurl {
      url = "https://proton.me/download/PassDesktop/darwin/universal/ProtonPass_1.33.0.dmg";
      sha256 = "sha256-zYQ7CV4tzpxkjO11oFzWTRy0CD4CDIVN6SL9VlhCUHQ=";
    };
  };
  protonvpn-bin = {
    pname = "protonvpn-bin";
    version = "6.1.0";
    src = fetchurl {
      url = "https://vpn.protondownload.com/download/macos/6.1.0/ProtonVPN_mac_v6.1.0.dmg";
      sha256 = "sha256-u/J32eIgpQkvF87j4Lc3IKT0YkJHTx4JauL6TsXg/ls=";
    };
  };
  swipeaerospace-bin = {
    pname = "swipeaerospace-bin";
    version = "0.2.5";
    src = fetchurl {
      url = "https://github.com/MediosZ/SwipeAeroSpace/releases/download/0.2.5/SwipeAeroSpace.zip";
      sha256 = "sha256-v3zjXCxCS2Vsjqoc+vYvbN3hiBKy2Jh+uIrG2ZSPmn0=";
    };
  };
  wheelwizard = {
    pname = "wheelwizard";
    version = "2.3.3";
    src = fetchgit {
      url = "https://github.com/TeamWheelWizard/WheelWizard.git";
      rev = "2.3.3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DuEI6bmvNP6wRuZX9Do0FGDsu80ldy0SCefBk6gqT9s=";
    };
  };
}
